#pragma once
#ifndef ARM_INCLUDES_HPP
#define ARM_INCLUDES_HPP
#include <armnnOnnxParser/IOnnxParser.hpp>
#include <armnn/ArmNN.hpp>
#include <armnnUtils/TContainer.hpp>
#include <armnnUtils/TensorIOUtils.hpp>
#include <armnn/Exceptions.hpp>
#include <armnnUtils/Permute.hpp>
#include <armnn/TypesUtils.hpp>
//#include <armnnUtils/HeapProfiling.hpp>
#include <opencv4/opencv2/opencv.hpp>
#include <vector>
#include <sstream>
#include <float.h>
#include <time.h>
#include <map>
#include <list>
#include <cmath>
#include <string>
#include <functional>
#include <tuple>
#include <iostream>
#include <fstream>
#include <NumCpp.hpp>
#include <array>
#include <utility>
#include <cstdint>

using std::vector;
using std::array;
using std::declval;
using std::list;
using std::string;
using std::function;
using std::tuple;
using std::ifstream;
using std::ofstream;
using std::function;
using std::map;
#endif