#pragma once
#ifndef ARM_INCLUDES_HPP
#define ARM_INCLUDES_HPP
#include <armnn/ArmNN.hpp>
#include <armnnOnnxParser/IOnnxParser.hpp>
#include <opencv4/opencv2/opencv.hpp>
#include <vector>
#include <stdint.h>
#include <map>
#include <list>
#include <cmath>
#include <string>
#include <functional>
#include <array>
#include <tuple>
#include <iostream>
#include <fstream>
#include <NumCpp.hpp>

using std::vector;
using std::list;
using std::string;
using std::function;
using std::tuple;
using std::ifstream;
using std::ofstream;
using std::function;
using std::map;
#endif